# Generated by Django 5.2.3 on 2026-02-14 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_image_image_alter_image_is_primary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='is_primary',
            field=models.BooleanField(default=False),
        ),
    ]
