# Generated by Django 5.2.3 on 2026-02-15 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_category_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='icon',
        ),
    ]
