# Generated by Django 5.2.3 on 2025-06-19 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_title', models.CharField(default='Shop', max_length=255)),
                ('header_top', models.CharField(default='header top offer', max_length=255)),
                ('whatsapp_number', models.CharField(max_length=20)),
                ('messanger_url', models.URLField()),
                ('facebook_page_url', models.URLField()),
                ('tiktok_url', models.URLField()),
            ],
        ),
    ]
