# Generated by Django 5.2.3 on 2026-02-15 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='config',
            name='tiktok_url',
        ),
    ]
