# Generated by Django 5.2.3 on 2025-06-19 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_config'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='config',
            options={'verbose_name_plural': 'Configs'},
        ),
        migrations.AlterField(
            model_name='config',
            name='facebook_page_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='config',
            name='messanger_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='config',
            name='tiktok_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='config',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
