# Generated by Django 5.2.3 on 2025-06-19 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_config_options_alter_config_facebook_page_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='delivary_cost',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='config',
            name='delivary_cost_dhaka',
            field=models.IntegerField(default=0),
        ),
    ]
