# Generated by Django 5.2.3 on 2025-06-19 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_config_delivary_cost_config_delivary_cost_dhaka'),
    ]

    operations = [
        migrations.RenameField(
            model_name='config',
            old_name='delivary_cost',
            new_name='delivery_cost',
        ),
        migrations.RenameField(
            model_name='config',
            old_name='delivary_cost_dhaka',
            new_name='delivery_cost_dhaka',
        ),
    ]
