# Generated by Django 5.2.3 on 2025-06-19 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_config_about_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='config',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='config',
            name='phone',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='config',
            name='about_page',
            field=models.TextField(blank=True, default='\n<h2 class="font-bold text-left text-xl w-full">Our Mission:</h2>\n        <p class="py-3"> Lorem ipsum dolor sit amet consectetur adipisicing elit. Harum placeat odit, est eum dolorem\n            esse totam iusto necessitatibus eligendi illo doloribus vero aperiam atque tempora repudiandae molestiae\n            nemo distinctio quisquam! </p>\n        <div class="gap-3 grid grid-cols-1 lg:grid-cols-3"> <img class="object-cover" src="/mission-family.e331843b.jpg"\n                alt="Family in living room"> <img class="object-cover" src="/mission-interior.6687104b.jpg"\n                alt="Interior"> <img class="object-cover" src="/mission-materials.de3dc493.jpg" alt="Materials"> </div>\n        <p class="py-3"> Lorem ipsum dolor sit amet consectetur adipisicing elit. Harum placeat odit, est eum dolorem\n            esse totam iusto necessitatibus eligendi illo doloribus vero aperiam atque tempora repudiandae molestiae\n            nemo distinctio quisquam! </p>\n        <h2 class="font-bold mt-3 text-left text-xl w-full">Our Vision:</h2>\n        <p class="py-3"> Lorem ipsum dolor sit amet consectetur adipisicing elit. Harum placeat odit, est eum dolorem\n            esse totam iusto necessitatibus eligendi illo doloribus vero aperiam atque tempora repudiandae molestiae\n            nemo distinctio quisquam! </p>\n        <h2 class="font-bold mt-3 text-left text-xl w-full">Our Values:</h2>\n        <p class="py-3"> Lorem ipsum dolor sit amet consectetur adipisicing elit. Harum placeat odit, est eum dolorem\n            esse totam iusto necessitatibus eligendi illo doloribus vero aperiam atque tempora repudiandae molestiae\n            nemo distinctio quisquam! </p>\n        <div class="gap-3 grid grid-cols-1 lg:grid-cols-3"> <img class="object-cover" src="/mission-family.e331843b.jpg"\n                alt="Family in living room"> <img class="object-cover" src="/mission-interior.6687104b.jpg"\n                alt="Interior"> <img class="object-cover" src="/mission-materials.de3dc493.jpg" alt="Materials"> </div>\n', null=True),
        ),
    ]
